# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [3]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / sum_exp_x
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [5]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x = 1 / (1 + np.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    softmax_x = softmax(x)
    # 添加极小值，避免 log(0)
    #softmax_x = np.clip(softmax_x, 1e-10, 1.0)
    loss_sum = -np.sum(label * np.log(softmax_x),axis=-1)
    loss = np.mean(loss_sum)

    return loss

# 生成测试数据
test_data = np.random.normal(size=[10, 5])

# 生成 one-hot 编码的 label
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)] = 1.0

# 使用 TensorFlow 计算 softmax 交叉熵损失
tf_loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=label, logits=test_data))

# 使用自定义的 softmax 交叉熵损失函数
custom_loss = softmax_ce(test_data, label)

# 比较结果
print(((tf_loss - custom_loss) ** 2 < 0.0001).numpy())

True


## 实现 sigmoid 交叉熵loss函数

In [45]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    #sigmoid_x = sigmoid(x)
    # 添加极小值，避免 log(0)
    #sigmoid_x = np.clip(sigmoid_x, 1e-10, 1.0 - 1e-10)
    loss_sum =  -(label*np.log(x) + (1-label)*np.log(1-x))
    loss = np.mean(loss_sum)
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

print (sigmoid_ce(prob, label))
print(tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data)))

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
0.8975424447735744
tf.Tensor(0.8975424447735746, shape=(), dtype=float64)


True